FROM python:3.10-slim

WORKDIR /app
RUN apt-get update && apt-get install -y libgl1 libglib2.0-0
RUN pip install --no-cache-dir \
    opencv-python \
    ultralytics \
    pika \
    torch \
    torchvision \
    --extra-index-url https://download.pytorch.org/whl/cpu

COPY worker ./worker


CMD ["python", "-m", "worker.worker"]
